### ISSUE TITLE
[RBAC]: Paula unable to see custom template

### ISSUE THREAD

**Issue by tkam8** [nmenant/f5-cloud-edition-lab#41]
##### ISSUE TYPE
 - Bug Report

##### DOCUMENTATION LOCATION
http://f5-ce-lab.readthedocs.io/en/master/class1/module2/lab3.html

##### SUMMARY
Paula is unable to see the custom template created by Marco

![image](https://user-images.githubusercontent.com/19481266/41145631-bc7701e4-6b3b-11e8-9df4-28e036cb1d23.png)

Paula's current role assignments:
![image](https://user-images.githubusercontent.com/19481266/41145646-c843ebb8-6b3b-11e8-82b9-00fffcf159d2.png)

##### SUGGESTION
Add "Service Catalog Viewer" role or similar to allow Paula to see the custom role

![image](https://user-images.githubusercontent.com/19481266/41145677-e649b0c0-6b3b-11e8-8622-6ce6e6197047.png)

After doing that, Paula can see it:
![image](https://user-images.githubusercontent.com/19481266/41145703-f35d24cc-6b3b-11e8-807b-1b5c1d344af5.png)

**Comment by rjouhann** [comment]
I did a bit differently, added the custom template to role assigned to Paula. This is more the workflow we want our customer to use.

![image](https://user-images.githubusercontent.com/25542366/41165957-e14b5e22-6af3-11e8-955b-751176b63256.png)
